### ISSUE TITLE
Accuracy on WEBEmo

### ISSUE THREAD

**Issue by ggcr** [exped1230/S2-VER#1]
Hi,

Congratulations on the paper! It was a pleasure to read.

I have a question regarding the evaluation. You trained on WEBEmo and evaluated on UnbiasedEmo and Emotion6, which were created by the same authors as WEBEmo. However, I was wondering if you also evaluated on the 25 categories of WEBEmo itself?

On a side note, did you consider using Parrot’s emotion mapping to evaluate on UnbiasedEmo? Specifically, training on WEBEmo using the third hierarchical level (25 categories) and then mapping those results back to the second level (8 categories) to evaluate on UnbiasedEmo?

May I also know how many Total Params (B) does S^2-VER has?

**Comment by exped1230** [comment]
Thank you for your attention. First, since the images from WEBEmo are used as unlabeled samples and the pseudo labels are predicted based on the categories of two small-scale datasets, hence the inference based on 25 categories of WEBEmo actually is unfair. Therefore, we did not compare them with other methods. Maybe using the weight to initialize the model, then training on the WEBEmo dataset with 25 categories may achieves better performance.
Second, I agree with you that the training method may be effective, which involves first training with fine-grained emotions, then predict coarse-grained emotions. But I suggest treating the two granularity emotion classification tasks as multi-task during training, which may have better performance.
Third, the parameters of S2-VER is very similar to the ResNet-50, with only an additional linear layer for feature extraction. Its storage overhead during training mainly comes from the intermediate variables in the continuous contrastive learning.

**Comment by ggcr** [comment]
Thank you so much for such detailed answer.
